/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FetchProImport } from './routes/fetch-pro'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FetchProRoute = FetchProImport.update({
  id: '/fetch-pro',
  path: '/fetch-pro',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fetch-pro': {
      id: '/fetch-pro'
      path: '/fetch-pro'
      fullPath: '/fetch-pro'
      preLoaderRoute: typeof FetchProImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fetch-pro': typeof FetchProRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fetch-pro': typeof FetchProRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fetch-pro': typeof FetchProRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fetch-pro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fetch-pro'
  id: '__root__' | '/' | '/fetch-pro'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FetchProRoute: typeof FetchProRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FetchProRoute: FetchProRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fetch-pro"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fetch-pro": {
      "filePath": "fetch-pro.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
