/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FetchProImport } from './routes/fetch-pro'
import { Route as IndexImport } from './routes/index'
import { Route as ChangesReact19IndexImport } from './routes/changes-react-19/index'
import { Route as ChangesReact19ApiUseImport } from './routes/changes-react-19/api-use'

// Create/Update Routes

const FetchProRoute = FetchProImport.update({
  id: '/fetch-pro',
  path: '/fetch-pro',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChangesReact19IndexRoute = ChangesReact19IndexImport.update({
  id: '/changes-react-19/',
  path: '/changes-react-19/',
  getParentRoute: () => rootRoute,
} as any)

const ChangesReact19ApiUseRoute = ChangesReact19ApiUseImport.update({
  id: '/changes-react-19/api-use',
  path: '/changes-react-19/api-use',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fetch-pro': {
      id: '/fetch-pro'
      path: '/fetch-pro'
      fullPath: '/fetch-pro'
      preLoaderRoute: typeof FetchProImport
      parentRoute: typeof rootRoute
    }
    '/changes-react-19/api-use': {
      id: '/changes-react-19/api-use'
      path: '/changes-react-19/api-use'
      fullPath: '/changes-react-19/api-use'
      preLoaderRoute: typeof ChangesReact19ApiUseImport
      parentRoute: typeof rootRoute
    }
    '/changes-react-19/': {
      id: '/changes-react-19/'
      path: '/changes-react-19'
      fullPath: '/changes-react-19'
      preLoaderRoute: typeof ChangesReact19IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fetch-pro': typeof FetchProRoute
  '/changes-react-19/api-use': typeof ChangesReact19ApiUseRoute
  '/changes-react-19': typeof ChangesReact19IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fetch-pro': typeof FetchProRoute
  '/changes-react-19/api-use': typeof ChangesReact19ApiUseRoute
  '/changes-react-19': typeof ChangesReact19IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fetch-pro': typeof FetchProRoute
  '/changes-react-19/api-use': typeof ChangesReact19ApiUseRoute
  '/changes-react-19/': typeof ChangesReact19IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fetch-pro'
    | '/changes-react-19/api-use'
    | '/changes-react-19'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fetch-pro' | '/changes-react-19/api-use' | '/changes-react-19'
  id:
    | '__root__'
    | '/'
    | '/fetch-pro'
    | '/changes-react-19/api-use'
    | '/changes-react-19/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FetchProRoute: typeof FetchProRoute
  ChangesReact19ApiUseRoute: typeof ChangesReact19ApiUseRoute
  ChangesReact19IndexRoute: typeof ChangesReact19IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FetchProRoute: FetchProRoute,
  ChangesReact19ApiUseRoute: ChangesReact19ApiUseRoute,
  ChangesReact19IndexRoute: ChangesReact19IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fetch-pro",
        "/changes-react-19/api-use",
        "/changes-react-19/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fetch-pro": {
      "filePath": "fetch-pro.tsx"
    },
    "/changes-react-19/api-use": {
      "filePath": "changes-react-19/api-use.tsx"
    },
    "/changes-react-19/": {
      "filePath": "changes-react-19/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
